spring:
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    username: sa
    url: jdbc:h2:mem:testdb
    data: data.sql
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
