spring:
  datasource:
    driverClassName: org.h2.Driver
    password: sa
    username: sa
    url: jdbc:h2:mem:testdb
    data: classpath:database/data.sql
    schema: classpath:database/schema.sql
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: ${PORT:8080}
